#@TYPE: Machine
#@NAME: amd-zynq
#@DESCRIPTION: Machine configuration for AMD Zynq-7000 SoC

WRL_ZYNQ_BOOTBIN_TARGET ?= ""
require ${@bb.utils.contains_any('WRL_ZYNQ_BOOTBIN_TARGET', 'zc702 zc706', 'amd-zynq-sdt.inc', 'amd-zynq-basic.inc', d)}

# To eliminate the annoying output by meta-xilinx-standalone/classes/sanity-meta-xilinx-standalone.bbclass
XILINX_WITH_ESW ?= "xsct"

BSP_XILINX_DERIVED:append = " amd-zynq"

PREFERRED_PROVIDER_virtual/kernel ??= "linux-yocto"
PREFERRED_VERSION_linux-yocto ?= "6.12%"
PREFERRED_VERSION_linux-yocto-rt ?= "6.12%"

KERNEL_DEVICETREE = "xilinx/zynq-zc706.dtb xilinx/zynq-zc702.dtb "

#QSPI flash has 64kB erase size
EXTRA_IMAGECMD:jffs2 = "-lnp -e64KiB"

MACHINE_EXTRA_RRECOMMENDS = " kernel-modules kernel-devicetree"
IMAGE_FSTYPES += "tar.bz2 wic wic.bmap"
WKS_FILE = "zynq-sdimage.wks"
do_image_wic[depends] += "mtools-native:do_populate_sysroot dosfstools-native:do_populate_sysroot"
